export const ADD_BLOG_POST = "ADD_BLOG_POST";
export const DELETE_BLOG_POST = "DELETE_BLOG_POST";
export const PUT_BLOG_POST = "PUT_BLOG_POST";
export const GET_BLOG_POST_LIST = "GET_BLOG_POST_LIST";
export const GET_BLOG_POST_LIST_BY_CATEGORY = "GET_BLOG_POST_LIST_BY_CATEGORY";